dist: xenial

sudo: required

language: python

python:
  - "3.8.2"


install:
  - python --version
  - pip install cloudmesh-installer
  - cloudmesh-installer get storage
  - ls
  - pwd

script:
  - mkdir -p ~/.cloudmesh
  - wget -P ~/.cloudmesh https://raw.githubusercontent.com/cloudmesh/cloudmesh-configuration/master/cloudmesh/configuration/etc/cloudmesh.yaml
  - pytest -v --capture=no test_01_storage_size.py
  - pytest -v --capture=no test_02_storage_installer.py
  - pytest -v --capture=no test_03_storage_local.py
  - pytest -v --capture=no test_04_storage_copy.py
